/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectDetailsRouteImport } from './routes/project-details'
import { Route as ProblemCriteriaRouteImport } from './routes/problem-criteria'
import { Route as DetailedDesignRouteImport } from './routes/detailed-design'
import { Route as DesignSelectionRouteImport } from './routes/design-selection'
import { Route as DesignOptionsRouteImport } from './routes/design-options'
import { Route as BackgroundRouteImport } from './routes/background'
import { Route as IndexRouteImport } from './routes/index'

const ProjectDetailsRoute = ProjectDetailsRouteImport.update({
  id: '/project-details',
  path: '/project-details',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemCriteriaRoute = ProblemCriteriaRouteImport.update({
  id: '/problem-criteria',
  path: '/problem-criteria',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailedDesignRoute = DetailedDesignRouteImport.update({
  id: '/detailed-design',
  path: '/detailed-design',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSelectionRoute = DesignSelectionRouteImport.update({
  id: '/design-selection',
  path: '/design-selection',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignOptionsRoute = DesignOptionsRouteImport.update({
  id: '/design-options',
  path: '/design-options',
  getParentRoute: () => rootRouteImport,
} as any)
const BackgroundRoute = BackgroundRouteImport.update({
  id: '/background',
  path: '/background',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/background': typeof BackgroundRoute
  '/design-options': typeof DesignOptionsRoute
  '/design-selection': typeof DesignSelectionRoute
  '/detailed-design': typeof DetailedDesignRoute
  '/problem-criteria': typeof ProblemCriteriaRoute
  '/project-details': typeof ProjectDetailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/background': typeof BackgroundRoute
  '/design-options': typeof DesignOptionsRoute
  '/design-selection': typeof DesignSelectionRoute
  '/detailed-design': typeof DetailedDesignRoute
  '/problem-criteria': typeof ProblemCriteriaRoute
  '/project-details': typeof ProjectDetailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/background': typeof BackgroundRoute
  '/design-options': typeof DesignOptionsRoute
  '/design-selection': typeof DesignSelectionRoute
  '/detailed-design': typeof DetailedDesignRoute
  '/problem-criteria': typeof ProblemCriteriaRoute
  '/project-details': typeof ProjectDetailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/background'
    | '/design-options'
    | '/design-selection'
    | '/detailed-design'
    | '/problem-criteria'
    | '/project-details'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/background'
    | '/design-options'
    | '/design-selection'
    | '/detailed-design'
    | '/problem-criteria'
    | '/project-details'
  id:
    | '__root__'
    | '/'
    | '/background'
    | '/design-options'
    | '/design-selection'
    | '/detailed-design'
    | '/problem-criteria'
    | '/project-details'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackgroundRoute: typeof BackgroundRoute
  DesignOptionsRoute: typeof DesignOptionsRoute
  DesignSelectionRoute: typeof DesignSelectionRoute
  DetailedDesignRoute: typeof DetailedDesignRoute
  ProblemCriteriaRoute: typeof ProblemCriteriaRoute
  ProjectDetailsRoute: typeof ProjectDetailsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/project-details': {
      id: '/project-details'
      path: '/project-details'
      fullPath: '/project-details'
      preLoaderRoute: typeof ProjectDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problem-criteria': {
      id: '/problem-criteria'
      path: '/problem-criteria'
      fullPath: '/problem-criteria'
      preLoaderRoute: typeof ProblemCriteriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detailed-design': {
      id: '/detailed-design'
      path: '/detailed-design'
      fullPath: '/detailed-design'
      preLoaderRoute: typeof DetailedDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-selection': {
      id: '/design-selection'
      path: '/design-selection'
      fullPath: '/design-selection'
      preLoaderRoute: typeof DesignSelectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-options': {
      id: '/design-options'
      path: '/design-options'
      fullPath: '/design-options'
      preLoaderRoute: typeof DesignOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background': {
      id: '/background'
      path: '/background'
      fullPath: '/background'
      preLoaderRoute: typeof BackgroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackgroundRoute: BackgroundRoute,
  DesignOptionsRoute: DesignOptionsRoute,
  DesignSelectionRoute: DesignSelectionRoute,
  DetailedDesignRoute: DetailedDesignRoute,
  ProblemCriteriaRoute: ProblemCriteriaRoute,
  ProjectDetailsRoute: ProjectDetailsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
