/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectDetailsRouteImport } from './routes/project-details'
import { Route as ProblemCriteriaRouteImport } from './routes/problem-criteria'
import { Route as BackgroundRouteImport } from './routes/background'
import { Route as IndexRouteImport } from './routes/index'

const ProjectDetailsRoute = ProjectDetailsRouteImport.update({
  id: '/project-details',
  path: '/project-details',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemCriteriaRoute = ProblemCriteriaRouteImport.update({
  id: '/problem-criteria',
  path: '/problem-criteria',
  getParentRoute: () => rootRouteImport,
} as any)
const BackgroundRoute = BackgroundRouteImport.update({
  id: '/background',
  path: '/background',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/background': typeof BackgroundRoute
  '/problem-criteria': typeof ProblemCriteriaRoute
  '/project-details': typeof ProjectDetailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/background': typeof BackgroundRoute
  '/problem-criteria': typeof ProblemCriteriaRoute
  '/project-details': typeof ProjectDetailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/background': typeof BackgroundRoute
  '/problem-criteria': typeof ProblemCriteriaRoute
  '/project-details': typeof ProjectDetailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/background' | '/problem-criteria' | '/project-details'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/background' | '/problem-criteria' | '/project-details'
  id:
    | '__root__'
    | '/'
    | '/background'
    | '/problem-criteria'
    | '/project-details'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackgroundRoute: typeof BackgroundRoute
  ProblemCriteriaRoute: typeof ProblemCriteriaRoute
  ProjectDetailsRoute: typeof ProjectDetailsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/project-details': {
      id: '/project-details'
      path: '/project-details'
      fullPath: '/project-details'
      preLoaderRoute: typeof ProjectDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problem-criteria': {
      id: '/problem-criteria'
      path: '/problem-criteria'
      fullPath: '/problem-criteria'
      preLoaderRoute: typeof ProblemCriteriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background': {
      id: '/background'
      path: '/background'
      fullPath: '/background'
      preLoaderRoute: typeof BackgroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackgroundRoute: BackgroundRoute,
  ProblemCriteriaRoute: ProblemCriteriaRoute,
  ProjectDetailsRoute: ProjectDetailsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
